name: Build Windows Executable

on:
  push:
    branches: [ main ] # Запускать при пуше в основную ветку

jobs:
  build:
    runs-on: windows-latest # Запускаем на виртуальной машине с Windows

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pyqt6 openpyxl

    - name: Build executable
      run: |
        pyinstaller --name "NetworkDesigner" --onefile --windowed --add-data "main_window.ui;." main_app.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Windows-Executable
        path: dist/NetworkDesigner.exe